name: vib_sns
description: StreetPass-inspired social app prototype built with Flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  cloud_functions: ^5.1.3
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  flutter_blue_plus: ^1.16.8
  flutter_ble_peripheral: ^1.2.6
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.0.7
  vibration: ^1.8.4
  firebase_storage: ^12.3.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  image: ^4.5.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  gal: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/emoji/noto/
    - assets/stamp_sakura.png
    - assets/stamp_roses.png
    - assets/stamp_sprout.png
